# Generated by Django 6.1 on 2026-08-21 07:33

import apps.events.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=190, unique=True)),
                ('event_type', models.CharField(default='General', max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_image', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_color', models.CharField(default='#1C3A2E', max_length=20)),
                ('accent_color', models.CharField(default='#FFFDD0', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('public_token', models.CharField(default=apps.events.models._token, max_length=48, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=190, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('seats', models.IntegerField(default=1)),
                ('invitation_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('viewed', 'Viewed'), ('rsvp_yes', 'RSVP Yes'), ('rsvp_no', 'RSVP No'), ('checked_in', 'Checked In')], default='pending', max_length=15)),
                ('rsvp_token', models.CharField(default=apps.events.models._token, max_length=48, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='events.event')),
            ],
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user'], name='idx_events_owner'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='idx_events_status'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['event'], name='idx_guests_event'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['phone'], name='idx_guests_phone'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['invitation_status'], name='idx_guests_status'),
        ),
    ]
