# Generated by Django 6.0.4 on 2026-08-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_manage_events', 'Can manage events'), ('can_manage_guests', 'Can manage guests'), ('can_manage_finance', 'Can manage pledges and payments'), ('can_manage_messaging', 'Can manage messages and cards'), ('can_manage_settings', 'Can manage system settings')]},
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
